spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/auth/realms/deliveryapi
  datasource:
    username: sa
    url: jdbc:h2:./db/delivery;DB_CLOSE_ON_EXIT=FALSE
    hikari:
      maximum-pool-size: 25
      minimum-idle: 1
  h2:
    console.enabled: true
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update

server:
  forward-headers-strategy: native
  port: 8000
  servlet:
    context-path: "/"


logging:
  level:
    org.jgroups: INFO
    org.infinispan: INFO
    org.keycloak: INFO
    org.keycloak.services.managers.DefaultBruteForceProtector: DEBUG
    org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner: DEBUG
    org.keycloak.services.managers.UserSessionManager: DEBUG
    org.keycloak.timer.basic: DEBUG


keycloak:
  custom:
    server:
      keycloak-path: "/auth"
    adminUser:
      username: admin
      password: admin
      create-admin-user-enabled: true


management:
  endpoints:
    web:
      exposure:
        include: health, metrics, loggers